#!/bin/bash

cp -r setup archlive/airootfs

cd archlive
sudo ./build.sh -v

iso_path=$(ls archlive/out/archlinux-*.iso | grep iso)

dd bs=4M if=$iso_path of=/dev/sdx status=progress oflag=sync

echo Complete!
