#!/bin/bash

# pull config
source ./config

# get best mirrors
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.backup
rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
vim /etc/pacman.d/mirrorlist

# install yay
mkdir ~/dev && cd ~/dev
git clone https://aur.archlinux.org/yay.git
cd yay && makepkg -si

# install packages
yay -S $DEFAULT_PACKAGES

# get dotfiles
cd ~
git clone $DOTFILE_GIT -o .dotfiles
cd .dotfiles
sh $DOTFILE_SCRIPT
