#!/bin/bash

# pull config
source ./config/config

# larger font
setfont sun12x22

# update system clock
timedatectl set-ntp true

# encrypt partition
echo -en "$DRIVE_PASSPHRASE" | cryptsetup -c aes-xts-plain -y -s 512 luksFormat "$ROOT_DRIVE"
echo -en "$DRIVE_PASSPHRASE" | cryptsetup luksOpen "$ROOT_DRIVE" $CRYPT_NAME

pvcreate /dev/mapper/$CRYPT_NAME
vgcreate arch /dev/mapper/$CRYPT_NAME
lvcreate -l +100%FREE arch -n root

# Create filesystems on your encrypted partitions
mkfs.ext4 /dev/mapper/$CRYPT_NAME

# mount filesystems
mount /dev/mapper/$CRYPT_NAME /mnt
mkdir /mnt/boot
mount $BOOT_DRIVE /mnt/boot

# bootstrapping
pacstrap /mnt base base-devel networkmanager

if [[ $ISINTEL ]] then;
	pacstrap /mnt intel-ucode
fi

# fstab
genfstab -U /mnt >> /mnt/etc/fstab

# system setup
arch-chroot /mnt
ln -sf $MYLOCALE /etc/localtime
hwclock --systohc

# set root password
echo -en "$ROOT_PASSWORD\n$ROOT_PASSWORD" | passwd

# create user
useradd -m -g wheel -s /bin/bash $USERNAME
echo -en "$USERPW\n$USERPW" | passwd $USERNAME

# config files
sed -i $MYLOCALESED /etc/locale.gen && locale-gen
echo $MYHOSTNAME > /etc/hostname
echo $MYLANG >> /etc/locale.conf
echo $MYLANGUAGE >> /etc/locale.conf
cat /etc/hosts ./config/hosts > /etc/hosts
sed -i -e "s/<MYHOSTNAME>/$MYHOSTNAME/g" /etc/hosts

# modify MKINITCPIO
cp -f ./config/mkinitcpio /etc/mkinitcpio.conf
mkinitcpio -p linux

# setup BOOTLOADER
bootctl --path=/boot install
cp -f ./config/boot /boot/loader/loader
cp -f ./config/arch_boot /boot/loader/entries/arch

LUKSUUID=$(blkid -s UUID -o value $ROOT_DRIVE)
if [[ $ISINTEL ]] then;
	INTEL_IMAGE="initrd	/intel-ucode.img"
fi

sed -i -e "s/<LUKSUUID>/$LUKSUUID/g" /boot/loader/entries/arch
sed -i -e "s/<INTEL_IMAGE>/$INTEL_IMAGE/g" /boot/loader/entries/arch
sed -i -e "s/<MAP_DRIVE>/$MAP_DRIVE/g" /boot/loader/entries/arch

# finish and reboot
exit
cp ./post_install /mnt/user/$USERNAME/post_install
cp ./config/config /mnt/user/$USERNAME/config
umount -R /mnt
reboot
